spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examinpi?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: racem.messaoudi@gmail.com
    password: vqslyxehzolbwyie
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8089
cors:
  authorized:
    client: "*"
# Google Maps API Key
google:
  maps:
    apiKey: AIzaSyAaFViO2_OJutNTQczF4fFzSue10WPB3HQ

# Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer